[theme]

# Primary accent color for interactive elements.
primaryColor = "#cc5500" #d33682

# Background color for the main content area.
backgroundColor = "#000000"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#586e75"

# Color used for almost all text.
textColor = "#cc5500" #fff
